# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtUploaded = QtWidgets.QLabel(self.centralwidget)
        self.txtUploaded.setGeometry(QtCore.QRect(290, 60, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtUploaded.setFont(font)
        self.txtUploaded.setObjectName("txtUploaded")
        self.btnDownload_video = QtWidgets.QPushButton(self.centralwidget)
        self.btnDownload_video.setGeometry(QtCore.QRect(0, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnDownload_video.setFont(font)
        self.btnDownload_video.setObjectName("btnDownload_video")
        self.btnUpload_video = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpload_video.setGeometry(QtCore.QRect(200, 0, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnUpload_video.setFont(font)
        self.btnUpload_video.setObjectName("btnUpload_video")
        self.btnDownload_history = QtWidgets.QPushButton(self.centralwidget)
        self.btnDownload_history.setGeometry(QtCore.QRect(540, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnDownload_history.setFont(font)
        self.btnDownload_history.setObjectName("btnDownload_history")
        self.txtNew = QtWidgets.QComboBox(self.centralwidget)
        self.txtNew.setGeometry(QtCore.QRect(0, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtNew.setFont(font)
        self.txtNew.setObjectName("txtNew")
        self.txtNew.addItem("")
        self.txtNew.addItem("")
        self.txtNew.addItem("")
        self.txtNameVideo = QtWidgets.QLabel(self.centralwidget)
        self.txtNameVideo.setGeometry(QtCore.QRect(10, 170, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txtNameVideo.setFont(font)
        self.txtNameVideo.setObjectName("txtNameVideo")
        self.btnBroadcast = QtWidgets.QPushButton(self.centralwidget)
        self.btnBroadcast.setGeometry(QtCore.QRect(500, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBroadcast.setFont(font)
        self.btnBroadcast.setObjectName("btnBroadcast")
        self.btnDeleteVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteVideo.setGeometry(QtCore.QRect(630, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDeleteVideo.setFont(font)
        self.btnDeleteVideo.setObjectName("btnDeleteVideo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 26))
        self.menubar.setObjectName("menubar")
        self.menuT_i_video_t_Youtobe = QtWidgets.QMenu(self.menubar)
        self.menuT_i_video_t_Youtobe.setObjectName("menuT_i_video_t_Youtobe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuT_i_video_t_Youtobe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtUploaded.setText(_translate("MainWindow", "Đã tải video"))
        self.btnDownload_video.setText(_translate("MainWindow", "Download Video"))
        self.btnUpload_video.setText(_translate("MainWindow", "Upload Video"))
        self.btnDownload_history.setText(_translate("MainWindow", "Lịch sử tải video"))
        self.txtNew.setItemText(0, _translate("MainWindow", "Mới nhất"))
        self.txtNew.setItemText(1, _translate("MainWindow", "Cũ nhất"))
        self.txtNew.setItemText(2, _translate("MainWindow", "Theo tên"))
        self.txtNameVideo.setText(_translate("MainWindow", "Link ten bài hát "))
        self.btnBroadcast.setText(_translate("MainWindow", "Phát "))
        self.btnDeleteVideo.setText(_translate("MainWindow", "Xóa "))
        self.menuT_i_video_t_Youtobe.setTitle(_translate("MainWindow", "Tải video từ Youtobe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
